AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sns-s3-influxdb

  Sample SAM Template for sns-s3-influxdb

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  PythonPackages:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: python_packages
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7 
  WriteToInfluxDBFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: write_to_influxdb/
      Handler: app.lambda_handler
      Runtime: python3.7
      Layers:
        - !Ref PythonPackages
      Events:
        HelloWorld:
          Type: SNS # More info about SNS Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#sns
          Properties:
            Topic: arn:aws:sns:us-east-1:470049585876:NewFetchObject

Outputs:
  WriteToInfluxDBFunction:
    Description: "Write to InfluxDB Function ARN"
    Value: !GetAtt WriteToInfluxDBFunction.Arn
  WriteToInfluxDBFunctionIamRole:
    Description: "Implicit IAM Role created for Write to InfluxDB function"
    Value: !GetAtt WriteToInfluxDBFunctionRole.Arn
